# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    container.dumper.inline_factories: false
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Utils\RedisUtils:
        arguments:
            $redisConfig: '%redis.config%'

    # 短信实现类
    App\Service\Sms\MeiLianHuTong\SmsInterfaceImpl:
        arguments:
            $apiUrl: '%env(string:MEILIAN_API_URL)%'
            $user: '%env(string:MEILIAN_USER)%'
            $pass: '%env(string:MEILIAN_PASS)%'
            $apiKey: '%env(string:MEILIAN_APIKEY)%'

    # 短信接口类依赖实现
    App\Contract\SmsInterface: '@App\Service\Sms\MeiLianHuTong\SmsInterfaceImpl'


    # 支付实现类
    App\Service\Pay\AliPay\PayInterfaceImpl:
        arguments:
            $appId: '%env(string:ALIPAY_APP_ID)%'
            $appPrivateKey: '%env(string:ALIPAY_APP_PRIVATE_KEY)%'
            $alipayPublicKey: '%env(string:ALIPAY_ALIPAY_PUBLIC_KEY)%'
            $notifyUrl: '%env(string:ALIPAY_NOTIFY_URL)%'
            $encryptKey: '%env(string:ALIPAY_ENCRYPT_KEY)%'

    # 支付接口类依赖实现
    App\Contract\PayInterface: '@App\Service\Pay\AliPay\PayInterfaceImpl'
